---
package:
    name: nim
    version: "0.13.0"

source:
    git_url: git@github.com:nim-lang/Nim.git
    git_rev: v0.13.0

requirements:
    build:
        - gcc

test:
    requires:
        - node
    commands:
        - cd $SRC_DIR && ./koch tests

about:
    home: http://nim-lang.org/
    license: MIT
    license_file: copying.txt
    summary: A Compiler for the Nim programming language.
